name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  UV_VERSION: "0.6.1" # Pin uv version to avoid breaking changes

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Test environment variables - no real secrets needed anymore
      SUPABASE_PROJECT_REF: "abcdefghij1234567890"
      SUPABASE_DB_PASSWORD: "test-password-123"
      SUPABASE_ACCESS_TOKEN: "test-access-token"
      SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Create venv and install dependencies
        run: |
          # Create venv and install dependencies
          uv venv
          source .venv/bin/activate
          uv sync --group dev --frozen

      - name: Run tests
        run: |
          source .venv/bin/activate # necessary for pytest
          pytest --cov=supabase_mcp --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false

      - name: Build distribution packages
        run: |
          uv build --no-sources
          # Verify dist contains both wheel and tar.gz
          test -f dist/*.whl
          test -f dist/*.tar.gz
